import { join } from "node:path";

import consola from "consola";

import { execSafe, fileExists, ghRaw, git, readFile, writeFile } from "@towles/shared";
import { getConfig } from "../config.js";
import { ARTIFACTS } from "../prompt-templates/index.js";
import { log } from "../utils.js";
import type { IssueContext } from "../utils.js";
import type { ExecSafeFn } from "../labels.js";

export async function createPr(ctx: IssueContext, exec?: ExecSafeFn): Promise<string> {
  const cfg = getConfig();

  const existingUrl = await getExistingPrUrl(ctx.branch, exec);
  if (existingUrl) {
    log(`PR already exists: ${existingUrl}`);
    return existingUrl;
  }

  await git(["push", "-u", cfg.remote, ctx.branch]);

  const reviewPath = join(ctx.issueDir, ARTIFACTS.review);
  const reviewSummary = fileExists(reviewPath)
    ? readFile(reviewPath).slice(0, 2000)
    : "No review summary available.";

  const body = [
    "## Summary",
    "",
    `Automated implementation for: **${ctx.title}**`,
    "",
    `Closes #${ctx.number}`,
    "",
    "## Pipeline Artifacts",
    "",
    `- Plan: \`.auto-claude/issue-${ctx.number}/plan.md\``,
    `- Implementation: \`.auto-claude/issue-${ctx.number}/completed-summary.md\``,
    `- Simplify: \`.auto-claude/issue-${ctx.number}/simplify-summary.md\``,
    `- Review: \`.auto-claude/issue-${ctx.number}/review.md\``,
    "",
    "## Review Summary",
    "",
    reviewSummary,
    "",
    "---",
    "Generated by auto-claude pipeline",
  ].join("\n");

  const prUrl = await ghRaw(
    [
      "pr",
      "create",
      "--repo",
      cfg.repo,
      "--head",
      ctx.branch,
      "--title",
      ctx.title,
      "--body",
      body,
    ],
    exec,
  );

  if (!prUrl) {
    throw new Error("Failed to create PR — gh returned empty output");
  }

  writeFile(join(ctx.issueDir, ARTIFACTS.prUrl), prUrl);
  log(`PR created: ${prUrl}`);

  try {
    await attachArtifacts(ctx, prUrl, exec);
  } catch (e) {
    consola.warn(`Artifact upload failed (non-blocking): ${e}`);
  }

  return prUrl;
}

async function attachArtifacts(ctx: IssueContext, prUrl: string, exec?: ExecSafeFn): Promise<void> {
  const archivePath = join(ctx.issueDir, "artifacts.tar.gz");
  const tag = `ac-issue-${ctx.number}`;
  const cfg = getConfig();

  log("Archiving pipeline artifacts…");
  await execSafe("tar", [
    "czf",
    archivePath,
    "-C",
    ctx.issueDir,
    "--exclude=*.prompt.md",
    "--exclude=artifacts.tar.gz",
    ".",
  ]);

  log("Uploading artifacts to GitHub release…");
  await ghRaw(["release", "delete", tag, "--yes", "--repo", cfg.repo], exec);

  await ghRaw(
    [
      "release",
      "create",
      tag,
      "--prerelease",
      "--title",
      `Artifacts: #${ctx.number}`,
      "--repo",
      cfg.repo,
      archivePath,
    ],
    exec,
  );

  const assetUrl = await ghRaw(
    ["release", "view", tag, "--json", "assets", "--jq", ".assets[0].url", "--repo", cfg.repo],
    exec,
  );

  if (!assetUrl) {
    consola.warn("Could not get artifact download URL — skipping PR comment");
    return;
  }

  const comment = [
    "## Pipeline Artifacts",
    "",
    `[Download artifacts (tar.gz)](${assetUrl})`,
    "",
    "Contains: plan.md, completed-summary.md, simplify-summary.md, review.md",
  ].join("\n");

  await ghRaw(["pr", "comment", prUrl, "--body", comment], exec);
}

async function getExistingPrUrl(branch: string, exec?: ExecSafeFn): Promise<string | null> {
  const out = await ghRaw(
    [
      "pr",
      "list",
      "--repo",
      getConfig().repo,
      "--head",
      branch,
      "--state",
      "open",
      "--json",
      "url",
    ],
    exec,
  );
  try {
    const prs = JSON.parse(out) as Array<{ url: string }>;
    return prs.length > 0 ? prs[0].url : null;
  } catch {
    consola.debug(`Failed to parse PR list JSON for branch "${branch}"`);
    return null;
  }
}
