/** Slack shortcode → Unicode emoji; the character never crosses the wire. A
 * custom `:shipit:` renders literally — no `emoji:read` scope, and no
 * `emoji.slack-edge.com` fetch for the file proxy to allow through. */

export type EmojiGroup = {
  name: string;
  /** `[shortcode, character]`, in picker order. */
  entries: [string, string][];
};

export const EMOJI_GROUPS: EmojiGroup[] = [
  {
    name: "Smileys",
    entries: [
      ["grinning", "😀"],
      ["smiley", "😃"],
      ["smile", "😄"],
      ["grin", "😁"],
      ["laughing", "😆"],
      ["sweat_smile", "😅"],
      ["joy", "😂"],
      ["rolling_on_the_floor_laughing", "🤣"],
      ["relaxed", "☺️"],
      ["blush", "😊"],
      ["innocent", "😇"],
      ["slightly_smiling_face", "🙂"],
      ["upside_down_face", "🙃"],
      ["wink", "😉"],
      ["relieved", "😌"],
      ["heart_eyes", "😍"],
      ["kissing_heart", "😘"],
      ["yum", "😋"],
      ["stuck_out_tongue_winking_eye", "😜"],
      ["zany_face", "🤪"],
      ["money_mouth_face", "🤑"],
      ["hugging_face", "🤗"],
      ["thinking_face", "🤔"],
      ["zipper_mouth_face", "🤐"],
      ["neutral_face", "😐"],
      ["expressionless", "😑"],
      ["no_mouth", "😶"],
      ["smirk", "😏"],
      ["unamused", "😒"],
      ["roll_eyes", "🙄"],
      ["grimacing", "😬"],
      ["lying_face", "🤥"],
      ["pensive", "😔"],
      ["sleepy", "😪"],
      ["drooling_face", "🤤"],
      ["sleeping", "😴"],
      ["mask", "😷"],
      ["face_with_thermometer", "🤒"],
      ["nauseated_face", "🤢"],
      ["sneezing_face", "🤧"],
      ["hot_face", "🥵"],
      ["cold_face", "🥶"],
      ["dizzy_face", "😵"],
      ["exploding_head", "🤯"],
      ["cowboy_hat_face", "🤠"],
      ["partying_face", "🥳"],
      ["sunglasses", "😎"],
      ["nerd_face", "🤓"],
      ["confused", "😕"],
      ["worried", "😟"],
      ["slightly_frowning_face", "🙁"],
      ["open_mouth", "😮"],
      ["hushed", "😯"],
      ["astonished", "😲"],
      ["flushed", "😳"],
      ["pleading_face", "🥺"],
      ["frowning", "😦"],
      ["anguished", "😧"],
      ["fearful", "😨"],
      ["cold_sweat", "😰"],
      ["disappointed_relieved", "😥"],
      ["cry", "😢"],
      ["sob", "😭"],
      ["scream", "😱"],
      ["confounded", "😖"],
      ["persevere", "😣"],
      ["disappointed", "😞"],
      ["sweat", "😓"],
      ["weary", "😩"],
      ["tired_face", "😫"],
      ["yawning_face", "🥱"],
      ["triumph", "😤"],
      ["rage", "😡"],
      ["angry", "😠"],
      ["face_with_symbols_on_mouth", "🤬"],
      ["smiling_imp", "😈"],
      ["skull", "💀"],
      ["clown_face", "🤡"],
      ["ghost", "👻"],
      ["alien", "👽"],
      ["robot_face", "🤖"],
      ["see_no_evil", "🙈"],
      ["hear_no_evil", "🙉"],
      ["speak_no_evil", "🙊"],
    ],
  },
  {
    name: "Gestures",
    entries: [
      ["+1", "👍"],
      ["-1", "👎"],
      ["ok_hand", "👌"],
      ["v", "✌️"],
      ["crossed_fingers", "🤞"],
      ["love_you_gesture", "🤟"],
      ["metal", "🤘"],
      ["call_me_hand", "🤙"],
      ["point_left", "👈"],
      ["point_right", "👉"],
      ["point_up_2", "👆"],
      ["point_down", "👇"],
      ["raised_hand", "✋"],
      ["raised_hands", "🙌"],
      ["open_hands", "👐"],
      ["palms_up_together", "🤲"],
      ["handshake", "🤝"],
      ["pray", "🙏"],
      ["writing_hand", "✍️"],
      ["nail_care", "💅"],
      ["muscle", "💪"],
      ["clap", "👏"],
      ["wave", "👋"],
      ["eyes", "👀"],
      ["brain", "🧠"],
      ["ear", "👂"],
      ["person_shrugging", "🤷"],
      ["person_facepalming", "🤦"],
      ["person_raising_hand", "🙋"],
      ["person_gesturing_no", "🙅"],
      ["person_gesturing_ok", "🙆"],
      ["person_tipping_hand", "💁"],
      ["dancer", "💃"],
      ["man_dancing", "🕺"],
      ["walking", "🚶"],
      ["runner", "🏃"],
    ],
  },
  {
    name: "Hearts",
    entries: [
      ["heart", "❤️"],
      ["orange_heart", "🧡"],
      ["yellow_heart", "💛"],
      ["green_heart", "💚"],
      ["blue_heart", "💙"],
      ["purple_heart", "💜"],
      ["brown_heart", "🤎"],
      ["black_heart", "🖤"],
      ["white_heart", "🤍"],
      ["broken_heart", "💔"],
      ["two_hearts", "💕"],
      ["sparkling_heart", "💖"],
      ["heartpulse", "💗"],
      ["cupid", "💘"],
      ["gift_heart", "💝"],
      ["heavy_heart_exclamation", "❣️"],
      ["kiss", "💋"],
      ["100", "💯"],
      ["anger", "💢"],
      ["boom", "💥"],
      ["dizzy", "💫"],
      ["sweat_drops", "💦"],
      ["dash", "💨"],
      ["zzz", "💤"],
    ],
  },
  {
    name: "Celebration",
    entries: [
      ["tada", "🎉"],
      ["confetti_ball", "🎊"],
      ["balloon", "🎈"],
      ["birthday", "🎂"],
      ["gift", "🎁"],
      ["sparkles", "✨"],
      ["star", "⭐"],
      ["star2", "🌟"],
      ["fire", "🔥"],
      ["rocket", "🚀"],
      ["trophy", "🏆"],
      ["medal", "🏅"],
      ["crown", "👑"],
      ["gem", "💎"],
      ["champagne", "🍾"],
      ["clinking_glasses", "🥂"],
      ["beers", "🍻"],
      ["cake", "🍰"],
      ["pizza", "🍕"],
      ["taco", "🌮"],
      ["coffee", "☕"],
      ["tea", "🍵"],
      ["beer", "🍺"],
      ["wine_glass", "🍷"],
      ["cookie", "🍪"],
      ["doughnut", "🍩"],
      ["ice_cream", "🍨"],
      ["popcorn", "🍿"],
      ["apple", "🍎"],
      ["banana", "🍌"],
      ["strawberry", "🍓"],
    ],
  },
  {
    name: "Symbols",
    entries: [
      ["white_check_mark", "✅"],
      ["heavy_check_mark", "✔️"],
      ["ballot_box_with_check", "☑️"],
      ["x", "❌"],
      ["negative_squared_cross_mark", "❎"],
      ["heavy_plus_sign", "➕"],
      ["heavy_minus_sign", "➖"],
      ["question", "❓"],
      ["grey_question", "❔"],
      ["exclamation", "❗"],
      ["warning", "⚠️"],
      ["no_entry", "⛔"],
      ["stop_sign", "🛑"],
      ["bulb", "💡"],
      ["zap", "⚡"],
      ["bell", "🔔"],
      ["no_bell", "🔕"],
      ["lock", "🔒"],
      ["key", "🔑"],
      ["mag", "🔍"],
      ["hourglass", "⏳"],
      ["alarm_clock", "⏰"],
      ["calendar", "📅"],
      ["memo", "📝"],
      ["clipboard", "📋"],
      ["pushpin", "📌"],
      ["paperclip", "📎"],
      ["chart_with_upwards_trend", "📈"],
      ["chart_with_downwards_trend", "📉"],
      ["bar_chart", "📊"],
      ["moneybag", "💰"],
      ["credit_card", "💳"],
      ["package", "📦"],
      ["mailbox", "📫"],
      ["telephone", "☎️"],
      ["iphone", "📱"],
      ["computer", "💻"],
      ["desktop_computer", "🖥️"],
      ["floppy_disk", "💾"],
      ["camera", "📷"],
      ["headphones", "🎧"],
      ["speaker", "🔊"],
      ["mute", "🔇"],
      ["tv", "📺"],
      ["video_game", "🎮"],
      ["game_die", "🎲"],
      ["dart", "🎯"],
      ["soccer", "⚽"],
      ["basketball", "🏀"],
      ["football", "🏈"],
      ["baseball", "⚾"],
      ["tennis", "🎾"],
      ["bike", "🚲"],
      ["car", "🚗"],
      ["airplane", "✈️"],
      ["house", "🏠"],
      ["office", "🏢"],
      ["hospital", "🏥"],
      ["school", "🏫"],
    ],
  },
  {
    name: "Nature",
    entries: [
      ["dog", "🐶"],
      ["cat", "🐱"],
      ["mouse", "🐭"],
      ["rabbit", "🐰"],
      ["fox_face", "🦊"],
      ["bear", "🐻"],
      ["panda_face", "🐼"],
      ["koala", "🐨"],
      ["tiger", "🐯"],
      ["lion_face", "🦁"],
      ["cow", "🐮"],
      ["pig", "🐷"],
      ["frog", "🐸"],
      ["monkey_face", "🐵"],
      ["chicken", "🐔"],
      ["penguin", "🐧"],
      ["bird", "🐦"],
      ["duck", "🦆"],
      ["owl", "🦉"],
      ["bat", "🦇"],
      ["wolf", "🐺"],
      ["horse", "🐴"],
      ["unicorn_face", "🦄"],
      ["bee", "🐝"],
      ["bug", "🐛"],
      ["butterfly", "🦋"],
      ["snail", "🐌"],
      ["turtle", "🐢"],
      ["snake", "🐍"],
      ["octopus", "🐙"],
      ["fish", "🐟"],
      ["dolphin", "🐬"],
      ["whale", "🐳"],
      ["shark", "🦈"],
      ["crab", "🦀"],
      ["seedling", "🌱"],
      ["evergreen_tree", "🌲"],
      ["palm_tree", "🌴"],
      ["cactus", "🌵"],
      ["four_leaf_clover", "🍀"],
      ["maple_leaf", "🍁"],
      ["mushroom", "🍄"],
      ["rose", "🌹"],
      ["sunflower", "🌻"],
      ["blossom", "🌼"],
      ["tulip", "🌷"],
      ["earth_americas", "🌎"],
      ["sunny", "☀️"],
      ["partly_sunny", "⛅"],
      ["cloud", "☁️"],
      ["rain_cloud", "🌧️"],
      ["snowflake", "❄️"],
      ["snowman", "⛄"],
      ["rainbow", "🌈"],
      ["ocean", "🌊"],
      ["crescent_moon", "🌙"],
      ["night_with_stars", "🌃"],
    ],
  },
];

/** The row offered on hover — the reactions a DM actually gets. */
export const QUICK_REACTIONS = ["+1", "heart", "joy", "tada", "eyes", "pray"] as const;

/** Aliases arrive in `reactions` interchangeably with the canonical name. */
const ALIASES: Record<string, string> = {
  thumbsup: "+1",
  thumbsdown: "-1",
  thumbs_up: "+1",
  thumbs_down: "-1",
  smiling_face_with_3_hearts: "heart_eyes",
  laughing_face: "laughing",
  face_with_rolling_eyes: "roll_eyes",
  raised_hands_with_joy: "raised_hands",
  clapping: "clap",
  tada_parrot: "tada",
  heavy_exclamation_mark: "exclamation",
  white_check_mark_2: "white_check_mark",
  slightly_smiling: "slightly_smiling_face",
  simple_smile: "slightly_smiling_face",
  grinning_face: "grinning",
  raising_hands: "raised_hands",
  rofl: "rolling_on_the_floor_laughing",
  facepalm: "person_facepalming",
  shrug: "person_shrugging",
  thinking: "thinking_face",
};

const BY_SHORTCODE: Map<string, string> = new Map(EMOJI_GROUPS.flatMap((g) => g.entries));

/**
 * The character for a shortcode (colons optional), else `null`. `::skin-tone-N`
 * is dropped: the base character is right, a bare modifier is a stray swatch.
 */
export function emojiChar(shortcode: string): string | null {
  const name = shortcode
    .trim()
    .replace(/^:|:$/g, "")
    .replace(/::skin-tone-\d$/, "");
  if (!name || /^skin-tone-\d$/.test(name)) return null;
  return BY_SHORTCODE.get(name) ?? BY_SHORTCODE.get(ALIASES[name] ?? "") ?? null;
}

/** Picker search: matches a shortcode substring, so "par" finds `partying_face`. */
export function searchEmoji(query: string, limit = 60): [string, string][] {
  const q = query.trim().toLowerCase().replace(/^:|:$/g, "");
  if (!q) return [];
  const hits: [string, string][] = [];
  for (const [name, char] of BY_SHORTCODE) {
    if (name.includes(q)) hits.push([name, char]);
    if (hits.length >= limit) break;
  }
  return hits;
}
