name: Setup pnpm and Node.js
description: Install pnpm and Node.js with caching

inputs:
  node-version:
    description: Node.js version
    required: false
    default: "22"
  registry-url:
    description: npm registry URL (for publishing)
    required: false
    default: ""
  install-args:
    description: Additional args for pnpm install
    required: false
    default: ""

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4

    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm
        registry-url: ${{ inputs.registry-url }}

    - run: pnpm install ${{ inputs.install-args }}
      shell: bash
