packages:
  - playground
  - docs
  - packages/*
  - examples/*

overrides:
  vite: npm:rolldown-vite@latest
catalog: null

catalogs:
  cli:
    '@antfu/eslint-config': ^4.16.2
    '@anthropic-ai/claude-code': ^1.0.51
    '@anthropic-ai/sdk': ^0.56.0
    bumpp: ^10.2.0
    c12: ^3.0.4
    changelogen: ^0.6.2
    commander: ^14.0.0
    consola: ^3.4.2
    eslint: ^9.31.0
    fzf: ^0.5.2
    lint-staged: ^15.5.2
    magicast: ^0.3.5
    neverthrow: ^8.2.0
    prompts: ^2.4.2
    simple-git-hooks: ^2.13.0
    tsx: ^4.20.3
    typescript: ^5.8.3
    unbuild: ^3.5.0
    vite: ^6.3.5
    zod: ^4.0.5
  inlined:
    '@antfu/utils': ^9.2.0
  testing:
    vitest: ^3.2.4
    vitest-package-exports: ^0.1.1
    yaml: ^2.8.0
  types:
    '@types/node': catalog:types
    '@types/prompts': ^2.4.9
  utils:
    tinyexec: ^0.3.2

onlyBuiltDependencies:
  - '@anthropic-ai/claude-code'
