[package]
name = "tt-agent"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
dirs = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tt-exec = { workspace = true }

[lints]
workspace = true
