import { join } from "node:path";

import consola from "consola";

import { getConfig } from "../config.js";
import { ARTIFACTS, STEP_LABELS } from "../prompt-templates/index.js";
import { execSafe, fileExists, ghRaw, git, log, logStep, readFile, writeFile } from "../utils.js";
import type { IssueContext } from "../utils.js";

export async function stepCreatePR(ctx: IssueContext): Promise<boolean> {
  const cfg = getConfig();

  if (await hasOpenPR(ctx.branch)) {
    logStep(STEP_LABELS.createPr, ctx, true);
    return true;
  }

  logStep(STEP_LABELS.createPr, ctx);

  await git(["push", "-u", cfg.remote, ctx.branch]);

  const reviewPath = join(ctx.issueDir, ARTIFACTS.review);
  const reviewSummary = fileExists(reviewPath)
    ? readFile(reviewPath).slice(0, 2000)
    : "No review summary available.";

  const body = [
    "## Summary",
    "",
    `Automated implementation for: **${ctx.title}**`,
    "",
    `Closes #${ctx.number}`,
    "",
    "## Pipeline Artifacts",
    "",
    `- Research: \`.auto-claude/issue-${ctx.number}/research.md\``,
    `- Plan: \`.auto-claude/issue-${ctx.number}/plan.md\``,
    `- Implementation Plan: \`.auto-claude/issue-${ctx.number}/plan-implementation.md\``,
    `- Review: \`.auto-claude/issue-${ctx.number}/review.md\``,
    "",
    "## Review Summary",
    "",
    reviewSummary,
    "",
    "---",
    "Generated by auto-claude pipeline",
  ].join("\n");

  const prUrl = await ghRaw([
    "pr",
    "create",
    "--repo",
    cfg.repo,
    "--head",
    ctx.branch,
    "--title",
    ctx.title,
    "--body",
    body,
    "--label",
    cfg.triggerLabel,
  ]);

  if (prUrl) {
    const url = prUrl.trim();
    writeFile(join(ctx.issueDir, ARTIFACTS.prUrl), url);
    log(`PR created: ${url}`);

    try {
      await attachArtifacts(ctx, url);
    } catch (e) {
      consola.warn(`Artifact upload failed (non-blocking): ${e}`);
    }
  } else {
    consola.error("Failed to create PR");
    return false;
  }

  return true;
}

async function attachArtifacts(ctx: IssueContext, prUrl: string): Promise<void> {
  const archivePath = join(ctx.issueDir, "artifacts.tar.gz");
  const tag = `ac-issue-${ctx.number}`;
  const cfg = getConfig();

  // Create tar.gz (exclude resolved prompt templates and the archive itself)
  await execSafe("tar", [
    "czf",
    archivePath,
    "-C",
    ctx.issueDir,
    "--exclude=*.prompt.md",
    "--exclude=artifacts.tar.gz",
    ".",
  ]);

  // Delete old release if exists (idempotent)
  await execSafe("gh", ["release", "delete", tag, "--yes", "--repo", cfg.repo]);

  // Create pre-release with asset
  await execSafe("gh", [
    "release",
    "create",
    tag,
    "--prerelease",
    "--title",
    `Artifacts: #${ctx.number}`,
    "--repo",
    cfg.repo,
    archivePath,
  ]);

  // Get asset download URL
  const { stdout: assetUrl } = await execSafe("gh", [
    "release",
    "view",
    tag,
    "--json",
    "assets",
    "--jq",
    ".assets[0].url",
    "--repo",
    cfg.repo,
  ]);

  if (!assetUrl) {
    consola.warn("Could not get artifact download URL — skipping PR comment");
    return;
  }

  // Add PR comment with download link
  const comment = [
    "## Pipeline Artifacts",
    "",
    `[Download artifacts (tar.gz)](${assetUrl.trim()})`,
    "",
    "Contains: research.md, plan.md, plan-implementation.md, review.md, completed-summary.md",
  ].join("\n");

  await execSafe("gh", ["pr", "comment", prUrl, "--body", comment]);
}

async function hasOpenPR(branch: string): Promise<boolean> {
  const out = await ghRaw([
    "pr",
    "list",
    "--repo",
    getConfig().repo,
    "--head",
    branch,
    "--state",
    "open",
    "--json",
    "number",
  ]);
  try {
    const prs = JSON.parse(out);
    return Array.isArray(prs) && prs.length > 0;
  } catch {
    return false;
  }
}
