import { join } from "node:path";

import consola from "consola";

import { getConfig } from "../config.js";
import { ARTIFACTS, STEP_LABELS } from "../prompt-templates/index.js";
import { fileExists, ghRaw, git, log, logStep, readFile, writeFile } from "../utils.js";
import type { IssueContext } from "../utils.js";

export async function stepCreatePR(ctx: IssueContext): Promise<boolean> {
  const cfg = getConfig();

  if (await hasOpenPR(ctx.branch)) {
    logStep(STEP_LABELS.createPr, ctx, true);
    return true;
  }

  logStep(STEP_LABELS.createPr, ctx);

  await git(["push", "-u", cfg.remote, ctx.branch]);

  const reviewPath = join(ctx.issueDir, ARTIFACTS.review);
  const reviewSummary = fileExists(reviewPath)
    ? readFile(reviewPath).slice(0, 2000)
    : "No review summary available.";

  const body = [
    "## Summary",
    "",
    `Automated implementation for: **${ctx.title}**`,
    "",
    `Closes #${ctx.number}`,
    "",
    "## Pipeline Artifacts",
    "",
    `- Research: \`.auto-claude/issue-${ctx.number}/research.md\``,
    `- Plan: \`.auto-claude/issue-${ctx.number}/plan.md\``,
    `- Implementation Plan: \`.auto-claude/issue-${ctx.number}/plan-implementation.md\``,
    `- Review: \`.auto-claude/issue-${ctx.number}/review.md\``,
    "",
    "## Review Summary",
    "",
    reviewSummary,
    "",
    "---",
    "Generated by auto-claude pipeline",
  ].join("\n");

  const prUrl = await ghRaw([
    "pr",
    "create",
    "--repo",
    cfg.repo,
    "--head",
    ctx.branch,
    "--title",
    ctx.title,
    "--body",
    body,
    "--label",
    cfg.triggerLabel,
  ]);

  if (prUrl) {
    const url = prUrl.trim();
    writeFile(join(ctx.issueDir, ARTIFACTS.prUrl), url);
    log(`PR created: ${url}`);
  } else {
    consola.error("Failed to create PR");
    return false;
  }

  return true;
}

async function hasOpenPR(branch: string): Promise<boolean> {
  const out = await ghRaw([
    "pr",
    "list",
    "--repo",
    getConfig().repo,
    "--head",
    branch,
    "--state",
    "open",
    "--json",
    "number",
  ]);
  try {
    const prs = JSON.parse(out);
    return Array.isArray(prs) && prs.length > 0;
  } catch {
    return false;
  }
}
