#!/usr/bin/env node
// Give the *dev* app a real macOS bundle identity.
//
// macOS reads an app's name and Dock icon from the Info.plist of the `.app`
// its executable sits in. `tauri dev` builds a bare `target/debug/tt-app` and
// never bundles, so the Dock shows the generic Unix-executable icon (the one
// with "exec" written on it) and the menu bar says "tt-app". `npm start` fixes
// this by building the real `app` bundle target (see scripts/start.mjs), but
// dev can't: it needs the watch/HMR loop, which only exists in `tauri dev`.
//
// So we wrap the launch instead of the build. `tauri dev` runs the binary via
// `cargo run`, and cargo will hand the launch to a *runner* program when
// `CARGO_TARGET_<HOST_TRIPLE>_RUNNER` is set. We point that at a generated
// script that hardlinks whatever binary cargo just built into a throwaway
// `.app` skeleton and execs it from there — same PID (so `tauri dev`'s
// stop/restart still works), same binary (a hardlink, not a copy, so a
// several-hundred-MB debug build costs nothing per rebuild), but now with an
// Info.plist above it. The env var is set only on the `tauri dev` child, so
// it never leaks into `cargo test` or the user's own cargo commands.
//
// A broken checkout (no tauri.conf.json, no rustc) throws here rather than
// returning an error value: `tauri dev` cannot run under either condition, so
// there is no recoverable path for a caller to take.
import { chmodSync, cpSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import path from "node:path";

/**
 * Cargo-runner env for a `tauri dev` spawn — empty off macOS, where the
 * unbundled binary is exactly what every other platform wants.
 * @param {string} repoRoot
 * @returns {Record<string, string>}
 */
export function macosDevAppEnv(repoRoot) {
  if (process.platform !== "darwin") return {};

  const conf = readTauriConf(repoRoot);
  const runner = writeDevApp({
    dir: path.join(repoRoot, "target", "dev-app"),
    productName: conf.productName,
    identifier: conf.identifier,
    version: conf.version,
    icns: path.join(repoRoot, "crates-tauri", "tt-app", "icons", "icon.icns"),
  });
  return { [`CARGO_TARGET_${cargoTripleKey(hostTriple())}_RUNNER`]: runner };
}

/**
 * Write the `.app` skeleton and the runner script that launches through it.
 * Everything here is plain filesystem work — no macOS APIs — so it is
 * exercised by the unit test on any platform.
 * @param {object} spec
 * @param {string} spec.dir directory to hold the bundle and runner
 * @param {string} spec.productName
 * @param {string} spec.identifier
 * @param {string} spec.version
 * @param {string} spec.icns source `.icns` to copy into Resources
 * @returns {string} path to the runner script
 */
export function writeDevApp({ dir, productName, identifier, version, icns }) {
  const app = path.join(dir, `${productName}.app`);
  const macos = path.join(app, "Contents", "MacOS");
  const resources = path.join(app, "Contents", "Resources");
  mkdirSync(macos, { recursive: true });
  mkdirSync(resources, { recursive: true });

  // The executable is named after the product for the same reason the bundler
  // does it: an unbundled-looking name is what shows up in "Force Quit" and
  // Activity Monitor.
  writeFileSync(
    path.join(app, "Contents", "Info.plist"),
    infoPlist({ executable: productName, productName, identifier, version }),
  );
  cpSync(icns, path.join(resources, "icon.icns"));

  // Resolved relative to the script so the interpolation can't be broken by a
  // space (or anything else) in the repo path.
  const runner = path.join(dir, "run-app.sh");
  writeFileSync(
    runner,
    `#!/bin/sh
# Generated by scripts/macos-app.mjs — do not edit.
# Cargo runner: $1 is the binary it just built, the rest are the app's args.
set -e
bin="$1"
shift
exe="$(dirname "$0")/${productName}.app/Contents/MacOS/${productName}"
rm -f "$exe"
ln "$bin" "$exe" 2>/dev/null || cp "$bin" "$exe"
exec "$exe" "$@"
`,
  );
  chmodSync(runner, 0o755);
  return runner;
}

/**
 * @param {object} spec
 * @param {string} spec.executable
 * @param {string} spec.productName
 * @param {string} spec.identifier
 * @param {string} spec.version
 * @returns {string}
 */
function infoPlist({ executable, productName, identifier, version }) {
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleDevelopmentRegion</key><string>en</string>
  <key>CFBundleDisplayName</key><string>${productName}</string>
  <key>CFBundleExecutable</key><string>${executable}</string>
  <key>CFBundleIconFile</key><string>icon.icns</string>
  <key>CFBundleIdentifier</key><string>${identifier}</string>
  <key>CFBundleInfoDictionaryVersion</key><string>6.0</string>
  <key>CFBundleName</key><string>${productName}</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleShortVersionString</key><string>${version}</string>
  <key>CFBundleVersion</key><string>${version}</string>
  <key>NSHighResolutionCapable</key><true/>
</dict>
</plist>
`;
}

/**
 * Name, id and version come from tauri.conf.json rather than being restated
 * here, so the dev bundle and the one `npm start` builds can't drift apart.
 * @param {string} repoRoot
 * @returns {{productName: string, identifier: string, version: string}}
 */
function readTauriConf(repoRoot) {
  const file = path.join(repoRoot, "crates-tauri", "tt-app", "tauri.conf.json");
  /** @type {{productName?: string, identifier?: string, version?: string}} */
  const conf = JSON.parse(readFileSync(file, "utf8"));
  const { productName, identifier, version } = conf;
  if (!productName || !identifier || !version) {
    throw new Error(`[macos-app] ${file} is missing productName/identifier/version`);
  }
  return { productName, identifier, version };
}

/** @returns {string} e.g. `aarch64-apple-darwin` */
function hostTriple() {
  const out = execFileSync("rustc", ["-vV"], { encoding: "utf8" });
  const host = out.split("\n").find((line) => line.startsWith("host: "));
  if (!host) throw new Error("[macos-app] `rustc -vV` printed no host triple");
  return host.slice("host: ".length).trim();
}

/**
 * Cargo's env-var spelling of a target triple: uppercase, `-` → `_`.
 * @param {string} triple
 * @returns {string}
 */
export function cargoTripleKey(triple) {
  return triple.toUpperCase().replace(/-/g, "_");
}
