#!/usr/bin/env node
// Give the *dev* app a real macOS bundle identity: `tauri dev` never bundles, so
// the Dock shows the generic Unix-executable icon, and it can't use the `app`
// target `npm start` builds without losing watch/HMR. So wrap the launch —
// `CARGO_TARGET_<HOST_TRIPLE>_RUNNER` (set only on the `tauri dev` child) points
// cargo at a script that hardlinks the binary into a throwaway `.app`, same PID.
import { chmodSync, cpSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import path from "node:path";

/**
 * Cargo-runner env for a `tauri dev` spawn — empty off macOS.
 * @param {string} repoRoot
 * @returns {Record<string, string>}
 */
export function macosDevAppEnv(repoRoot) {
  if (process.platform !== "darwin") return {};

  const conf = readTauriConf(repoRoot);
  const runner = writeDevApp({
    dir: path.join(repoRoot, "target", "dev-app"),
    productName: conf.productName,
    identifier: conf.identifier,
    version: conf.version,
    icns: path.join(repoRoot, "crates-tauri", "tt-app", "icons", "icon.icns"),
  });
  return { [`CARGO_TARGET_${cargoTripleKey(hostTriple())}_RUNNER`]: runner };
}

/**
 * Plain filesystem work — no macOS APIs — so the unit test exercises it anywhere.
 * @param {{ dir: string; productName: string; identifier: string; version: string; icns: string }} spec
 * @returns {string} path to the runner script
 */
export function writeDevApp({ dir, productName, identifier, version, icns }) {
  const app = path.join(dir, `${productName}.app`);
  const macos = path.join(app, "Contents", "MacOS");
  const resources = path.join(app, "Contents", "Resources");
  mkdirSync(macos, { recursive: true });
  mkdirSync(resources, { recursive: true });

  // Named after the product because that is what "Force Quit" and Activity
  // Monitor show.
  writeFileSync(
    path.join(app, "Contents", "Info.plist"),
    infoPlist({ executable: productName, productName, identifier, version }),
  );
  cpSync(icns, path.join(resources, "icon.icns"));

  // Resolved relative to the script so the interpolation can't be broken by a
  // space (or anything else) in the repo path.
  const runner = path.join(dir, "run-app.sh");
  writeFileSync(
    runner,
    `#!/bin/sh
# Generated by scripts/macos-app.mjs — do not edit.
# Cargo runner: $1 is the binary it just built, the rest are the app's args.
set -e
bin="$1"
shift
exe="$(dirname "$0")/${productName}.app/Contents/MacOS/${productName}"
rm -f "$exe"
ln "$bin" "$exe" 2>/dev/null || cp "$bin" "$exe"
exec "$exe" "$@"
`,
  );
  chmodSync(runner, 0o755);
  return runner;
}

/** @param {{ executable: string; productName: string; identifier: string; version: string }} spec */
function infoPlist({ executable, productName, identifier, version }) {
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleDevelopmentRegion</key><string>en</string>
  <key>CFBundleDisplayName</key><string>${productName}</string>
  <key>CFBundleExecutable</key><string>${executable}</string>
  <key>CFBundleIconFile</key><string>icon.icns</string>
  <key>CFBundleIdentifier</key><string>${identifier}</string>
  <key>CFBundleInfoDictionaryVersion</key><string>6.0</string>
  <key>CFBundleName</key><string>${productName}</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleShortVersionString</key><string>${version}</string>
  <key>CFBundleVersion</key><string>${version}</string>
  <key>NSHighResolutionCapable</key><true/>
</dict>
</plist>
`;
}

/**
 * Read rather than restated so the dev bundle can't drift from `npm start`'s;
 * throws rather than returning a Result, since there is no recovery from it.
 * @param {string} repoRoot
 */
function readTauriConf(repoRoot) {
  const file = path.join(repoRoot, "crates-tauri", "tt-app", "tauri.conf.json");
  /** @type {{productName?: string, identifier?: string, version?: string}} */
  const conf = JSON.parse(readFileSync(file, "utf8"));
  const { productName, identifier, version } = conf;
  if (!productName || !identifier || !version) {
    throw new Error(`[macos-app] ${file} is missing productName/identifier/version`);
  }
  return { productName, identifier, version };
}

/** @returns {string} e.g. `aarch64-apple-darwin` */
function hostTriple() {
  const out = execFileSync("rustc", ["-vV"], { encoding: "utf8" });
  const host = out.split("\n").find((line) => line.startsWith("host: "));
  if (!host) throw new Error("[macos-app] `rustc -vV` printed no host triple");
  return host.slice("host: ".length).trim();
}

/**
 * Cargo's env-var spelling of a target triple: uppercase, `-` → `_`.
 * @param {string} triple
 * @returns {string}
 */
export function cargoTripleKey(triple) {
  return triple.toUpperCase().replace(/-/g, "_");
}
