name: PR Checks

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  pr-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: ./.github/actions/setup
      - run: bun run lint
      - run: bun run typecheck
      - run: bun run format:check
      - run: bun run test:prompts

  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest] # , windows-latest, macos-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: bun test
        env:
          CI: DisableCallingClaude
